# Create dependabot.yml file for dependabot to create pull requests #3843

name: Dependabot pull requests

version: 2
updates:
  - package-ecosystem: "npm"
    # Files stored in root directory
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    # Files stored in root directory
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github`
    directory: "/"
    schedule:
      interval: "weekly"
