version: 2
updates:
  - package-ecosystem: "npm"
    # NPM package directory
    directory: "/github-actions/trigger-schedule/github-data"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github`
    directory: "/"
    schedule:
      interval: "daily"
