version: 2
updates:
  - package-ecosystem: "npm"
    # Files stored in root directory
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    # Files stored in root directory
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github`
    directory: "/"
    schedule:
      interval: "daily"
