services:
  hfla_site:
    image: hackforlaops/ghpages:latest
    container_name: hfla_site
    command: >
      sh -c "jekyll clean &&
             jekyll serve --force_polling --livereload --config _config.yml,_config.docker.yml -I"
    environment:
      - JEKYLL_ENV=docker
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
  hfla_test:
    image: node:20-alpine
    container_name: hfla_test
    profiles: 
      - test
    volumes:
      - .:/website
    working_dir: /website/tests
    command: >
      sh -c "npm install jest jest-environment-jsdom liquidjs gray-matter magic-string --save-dev
             npm test"

    
