---
name: Project/Product Management
description: PMs from different projects come together in this group to share effective practices, give and get mentorship, set product management standards, and create guides and templates by discovering effective practices from all Hack for LA teams.
visible: true
status: Active
location:
  - Remote

image: /assets/images/communities-of-practice/product.jpg
alt: 'Several people around a small table listen intently as one person speaks.'

icon: /assets/images/hero/communities-icons/product-management.png

meeting-times: Fridays 12:00-1:00 pm PT

leadership-type: Mentor Led
leadership:
  - name: Bonnie Wolfe
    role: Lead
    links:
      slack: https://hackforla.slack.com/team/UE1UG1YFP
      github: https://github.com/experimentsinhonesty
    picture: https://avatars.githubusercontent.com/u/37763229
    
links:
  - name: Slack
    url: https://app.slack.com/client/T04502KQX/C010LNXH2JY/details/
  - name: Github
    url: https://github.com/hackforla/product-management

recruiting-message:
---
