---
name: Product Management
description: PMs from different projects come together in this group to share effective practices, give and get mentorship, set product management standards, and create guides and templates for new projects.
visible: true
status: Active
location:
  - Remote

image: /assets/images/communities-of-practice/product.jpg
alt: 'Several people around a small table listen intently as one person speaks.'

icon: /assets/images/communities-of-practice/homepage-icons/product-management.png

meeting-times: Tuesdays 6:00-7:00 pm PT

leadership-type: Mentor Led
leadership:
  - name: Niven Prasad
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U015R4RTDJA
      github: https://github.com/NivenPrasad
    picture: https://avatars.githubusercontent.com/u/61798667
  - name: Olivia Chiong
    role: Co-lead
    links:
      slack: https://hackforla.slack.com/team/U01GJC7VC6L
      github: https://github.com/Olivia-Chiong
    picture: https://avatars.githubusercontent.com/u/75456721

links:
  - name: Slack
    url: https://app.slack.com/client/T04502KQX/C010LNXH2JY/details/
  
recruiting-message:
---