name: Communities of Practice information updates
description: CoP leads use this issue to make changes to Leadership members and contact info
title: 'Communities of Practice information updates: [INSERT NAME OF Community of Practice]'
labels: ['role: product', 'P-Feature: Communities of Practice', 'time sensitive', 'Complexity: Missing', 'size: missing']
body:
  - type: markdown
    attributes:
      value: "### Overview"
  - type: markdown
    attributes:
      value: "As a Community of Practice Co-Lead, I need my CoP's details to be up to date on the HackforLA website."
  - type: markdown
    attributes:
      value: "### Action Items"
  - type: markdown
    attributes:
      value: "Change CoP name: NO"
  - type: markdown
    attributes:
      value: "Change Description: NO"
  - type: dropdown
    attributes:
      label: "Change Leadership Type"
      options:
        - "YES"
        - "NO"
      description: "If YES on Change Leadership Type, choose the Leadership Type; if NO, leave the field with the NA value:"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Leadership Type"
      options:
        - "N/A"
        - "Mentor Led"
        - "Community Led"
      default: 0
      description: "Select the type of leadership if applicable."
  - type: markdown
    attributes:
      value: "Change Slack Link: NO"
  - type: dropdown
    id: remove-person-yes-no
    attributes:
      label: "Remove person(s) and info from CoP file?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: remove-person
    attributes:
      label: "If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:"
      value: "Name:"
  - type: dropdown
    id: add-person-yes-no
    attributes:
      label: "Add person(s) and info to CoP file?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: add-persons
    attributes:
      label: "If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:"
      value: |
        Name:
        Title:
        GitHub Handle:
        Slack Member ID:
  - type: markdown
    attributes:
      value: |
        ### Resources
        * Folder where files are in the repo: https://github.com/hackforla/website/tree/gh-pages/_data/internal/communities
        * Where you can see the live page: https://www.hackforla.org/communities-of-practice
        * If you need to update your meeting times, names, dates, or frequency, please see the [VRMS User Guide](https://github.com/hackforla/VRMS/wiki/User-Guide). The HackforLA.org website gets the meeting times from the updates made to each Community of Practice's meeting data in vrms.io