name: 'Feasibility Issue Template '
description: 'Used to standardize issue forms '
title: 'Standard Feasibility Issue Template '


body:
  - type: input
    id: title
    attributes:
      label: "Title"
      description: "Enter the title of this issue"
    validations:
      required: true
  - type: dropdown
    id: dependency
    attributes:
      label: Is there a dependency?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: textarea
    id: dependency-explanation
    attributes:
      label: "If yes, please explain"
  # - type: markdown
  #   attributes:
  #     value: "## Dependencies"
  # - type: checkboxes
  #   id: checkbox-items
  #   attributes:
  #     label: "Indicate if there are dependencies associated with this issue"
  #     options:
  #       - label: "Dependency 1"
  #       - label: "Dependency 2"  
  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "Clearly state the purpose of this issue in 2 sentences or less"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "## Action Items"
  - type: markdown
    attributes:
      value: |
        - [ ] "Action Item 1"
        - [ ] "Action Item 2"
        - [ ] "Action Item 3"
  # - type: textarea
  #   id: action-items
  #   attributes:
  #     label: "Action Items"
  #     description: >-
  #       List the research to be done, or the steps to be completed. 
  #       Note: If the steps can be divided into tasks for more than one person, 
  #       we recommend dividing it up into separate issues, or assigning it as a pair programming task.
  #   validations:
  #     required: true
  - type: checkboxes
    id: feasibility-checklist
    attributes:
      label: "List feasibility related issues"
      options: 
        - label: "Check 1"
        - label: "Check 2"
        - label: "Check 3"
  - type: textarea
    id: feasibility-items
    attributes:
      label: "Feasibility Items"
    validations:
      required: true
  # - type: markdown
  #   attributes:
  #     value: "## Action Items"
  # - type: checkboxes
  #   id: items
  #   attributes:
  #     label: "List the research to be done, or the steps to be completed. Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task."
  #     options: 
  #       - label: "Instruction example 1"
  #       - label: "Instruction example 2"
  #       - label: "Instruction example 3"
  # - type: markdown
  #   attributes:
  #     value: "## Feasibility Checklist"
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc."
    validations:
      required: true