name: 'Feasibility Issue Template '
description: 'Used to standardize issue forms '
title: 'Standard Feasibility Issue Template '


body:
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Clearly state the purpose of this issue in 2 sentences or less
    validations:
      required: true
  - type: markdown
    id: dependencies
    attributes:
      label: "## Dependencies"
      description: Indicate if there are dependencies associated with this issue
  - type: checkboxes
    id: checkbox-items
    options:
      label: Dependency 1
      label: Dependency 2  
  - type: markdown
    id: action-items
    attributes:
      label: "## Action Items"
      description: "List the research to be done, or the steps to be completed. Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task."
  - type: checkboxes
    id: items
    options: 
      - label: "Instruction example 1"
      - label: "Instruction example 2"
      - label: "Instruction example 3"
    validations:
      required: true
  - type: markdown
    id: feasibility-checklist
    attributes:
      label: "## Feasibility Checklist"
      description: "List feasibility related issues."
  - type: checkboxes
    id: feasibility-items
    options: 
     - label: "Check 1"
     - label: "Check 2"
     - label: "Check 3"
     validations:
      required: true
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc."
    validations:
      required: true