name: 'Feasibility Issue Template '
description: 'Used to standardize issue forms '
title: 'Standard Feasibility Issue Template '


body:
  - type: textarea
    id: title
    attributes:
      label: "Title"
      description: "Enter the title of this issue"
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: "Overview"
      description: "Clearly state the purpose of this issue in 2 sentences or less"
    validations:
      required: true
  - type: dropdown
    id: dependency
    attributes:
      label: Is there a dependency?
      options:
        - "Yes"
        - "No"
  - type: markdown
    #id: dependencies
    attributes:
      value: "## Dependencies"
  - type: checkboxes
    id: checkbox-items
    attributes:
      label: "Indicate if there are dependencies associated with this issue"
      options:
        - label: "Dependency 1"
        - label: "Dependency 2"  
  - type: markdown
    #id: action-items
    attributes:
      value: "## Action Items"
  - type: checkboxes
    id: items
    attributes:
      label: "List the research to be done, or the steps to be completed. Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task."
      options: 
        - label: "Instruction example 1"
        - label: "Instruction example 2"
        - label: "Instruction example 3"
    # validations:
    #   required: true
  - type: markdown
    #id: feasibility-checklist
    attributes:
      value: "## Feasibility Checklist"
  - type: checkboxes
    id: feasibility-items
    attributes:
      label: "List feasibility related issues."
      options: 
        - label: "Check 1"
        - label: "Check 2"
        - label: "Check 3"
    # validations:
    #   required: true
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc."
    validations:
      required: true