name: "Project Profile Card review and update"
description: "To track project profile card updates or add a new project profile card"
title: "Update Project Profile: [Project Name]"
labels: ['P-Feature: Project Info and Page', 'role: back end/devOps', 'role: front end', 'Complexity: Small', 'size: 0.5pt', 'time sensitive']

body:
  - type: markdown
    attributes:
      value: "# Overview"
  - type: markdown
    attributes:
      value: "As a product manager, I want my project's details to be up to date on the Hack for LA website."
  - type: dropdown
    id: project-name
    attributes:
      label: Project Name
      options:
        - "---New Project---"
        - "100 Automations"
        - "311 Data"
        - "Access The Data"
        - "BallotNav"
        - "Brigade Organizers Playbook"
        - "Civic Opportunity Project"
        - "Civic Tech Index"
        - "Civic Tech Jobs"
        - "Civic Tech Structure"
        - "Design Systems"
        - "Engage"
        - "Expunge Assist"
        - "Food Oasis"
        - "GreenEarthOS"
        - "Guides Team"
        - "Hackforla.org Website"
        - "Home Unite Us"
        - "LA TDM Calculator"
        - "Lucky Parking"
        - "Open Community Survey"
        - "Tech Work Experience"
        - "VRMS"
        - "Write for All"
        - "Youth Justice Nav"
        - "EMS Triage Tracker"
        - "Heart"
        - "HelloGOV"
        - "Public Tree Map"
        - "Railstats LA"
        - "Undebate"
        - "Work for LA"
        - "Jobs for Hope"
        - "New Schools Today"
        - "Not Today - Self-Defense Against Suicidal Thoughts"
        - "Spare"
    validations:
      required: true
  
  - type: dropdown
    id: project-card-url
    attributes:
      label: Project Card URL
      description: "https://github.com/hackforla/website/tree/gh-pages/_projects"
      options: 
        - "---New Project---"
        - "100-automations.md"
        - "311-data.md"
        - "access-the-data.md"
        - "adopt-civic-art.md"
        - "ballot-nav.md"
        - "brigade-organizers-playbook.md"
        - "civic-opportunity-project.md"
        - "civic-tech-index.md"
        - "civic-tech-jobs.md"
        - "civic-tech-structure.md"
        - "criminal-sentencing.md"
        - "curbmap.md"
        - "design-systems.md"
        - "ems-triage-tracker.md"
        - "engage.md"
        - "expunge-assist.md"
        - "food-oasis.md"
        - "green-earth-os.md"
        - "guides-team.md"
        - "heart.md"
        - "hellogov.md"
        - "home-unite-us.md"
        - "jobs-for-hope.md"
        - "light-the-way.md"
        - "lucky-parking.md"
        - "metro-ontime.md"
        - "new-schools-today.md"
        - "not-today.md"
        - "open-community-survey.md"
        - "public-tree-map.md"
        - "shared-housing-project.md"
        - "spare.md"
        - "tdm-calculator.md"
        - "tech-work-experience.md"
        - "undebate.md"
        - "vrms.md"
        - "website.md"
        - "work-for-la.md"
        - "writeforall.md"
        - "youthjusticenav.md"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "# Action Items"

  - type: dropdown
    id: update-title-yes-no
    attributes:
      label: Update the Title?
      options: 
        - "YES"
        - "NO"
    validations:
      required: true
  - type: input
    id: title
    attributes:
      label: Title
  
  - type: dropdown
    id: update-description-yes-no
    attributes:
      label: Update the Description?
      options: 
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description

  - type: dropdown
    id: update-hero-image-yes-no
    attributes:
      label: Update the Hero Image?
      options: 
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: hero-image
    attributes:
      label: Hero Image

  - type: dropdown
    id: update-image-yes-no
    attributes:
      label: Update the Image?
      options: 
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: image
    attributes:
      label: Image

  - type: dropdown
    id: update-technologies-yes-no
    attributes:
      label: Update the Technologies?
      options: 
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: technologies
    attributes:
      label: Technologies (maximum 26 characters per technology name)

  - type: dropdown
    id: update-partners-yes-no
    attributes:
      label: Update the Partner(s)?
      options: 
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: partners
    attributes:
      label: Partners

  - type: dropdown
    id: update-tools-yes-no
    attributes:
      label: Update the Tools?
      options: 
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: tools
    attributes:
      label: Tools

  - type: dropdown
    id: update-github-link-yes-no
    attributes:
      label: "Update GitHub Link?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: input
    id: github-link
    attributes:
      label: GitHub Link
  
  - type: dropdown
    id: additional-github-repos-yes-no
    attributes:
      label: "Do you have any additional (other than your primary) GitHub repositories that your volunteers make issues or PRs against?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: additional-github-repos
    attributes:
      label: "If yes, list the repo URLs here"

  - type: dropdown
    id: update-slack-link-yes-no
    attributes:
      label: "Update Slack Link?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: input
    id: slack-link
    attributes:
      label: Slack Link

  - type: dropdown
    id: update-test-site-link-yes-no
    attributes:
      label: "Update Test Site Link?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: input
    id: test-site-link
    attributes:
      label: Test Site Link

  - type: dropdown
    id: update-demo-site-link-yes-no
    attributes:
      label: "Update Demo Site Link?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: input
    id: demo-site-link
    attributes:
      label: Demo Site Link

  - type: dropdown
    id: update-site-link-yes-no
    attributes:
      label: "Update Site Link?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: input
    id: site-link
    attributes:
      label: Site link

  - type: dropdown
    id: remove-leadership-yes-no
    attributes:
      label: "Remove person(s) and info from Leadership?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: remove-leadership
    attributes:
      label: "If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:"
      value: "Name:"

  - type: dropdown
    id: add-leadership-yes-no
    attributes:
      label: "Add person(s) and info to Leadership?"
      options:
        - "YES"
        - "NO"
    validations:
      required: true
  - type: textarea
    id: add-leadership
    attributes:
      label: "If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:"
      value: |
        Name:
        GitHub Handle:
        Role:
        Slack Member ID:

  - type: dropdown
    id: status
    attributes:
      label: Project Status
      options:
        - "Active"
        - "Completed"
        - "On Hold"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "### Resources"
  - type: markdown
    attributes:
      value: |
        If you need to update your meeting times, names, dates, or frequency, please see the [VRMS User Guide](https://github.com/hackforla/VRMS/wiki/User-Guide).  The HackforLA.org website gets the meeting times from the updates the Project PM makes to the project's meeting data in vrms.io

  - type: markdown
    attributes:
      value: "# Additional Instructions"
  
  - type: markdown
    attributes:
      value: |
        1. If only adding/removing person(s) from leadership, add the `ready for dev lead` label, otherwise add the `ready for org rep` label
        ![add_label](https://user-images.githubusercontent.com/73561520/201548934-161f8abc-0918-47a5-8b3b-d3327541d700.png)


        2. Add newly created issue to the Project Board.
        ![project_board](https://user-images.githubusercontent.com/73561520/201549346-7371ae37-cb56-4b40-8b66-1cd548bc3684.png)


