---
title: Environmental Impact
title-link: https://thenounproject.com/
content: Image
used-in: About
artist: Made x Made
provider: Noun Project
provider-link: https://thenounproject.com/search/?q=impact&i=1710368
image-url: /assets/images/about/platform-header-elements/impact.svg
alt: 'Image of Global'
type: icon
---