name: Add Missing Labels To Issues
on:
  issues:
    types: [opened]

jobs:
  Add-Missing-Labels-To-Issues:
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        uses: actions/github-script@v4
        id: check-labels
        with:
          script: |
            const script = require('./github-actions/issue-labels/check-labels.js')
            const checkLabels = script({g: github, c: context})
            return checkLabels