name: Add Missing Labels To Issues
on:
  issues:
    types: [opened]

jobs:
  Add-Missing-Labels-To-Issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Check if the issue has required labels
      - name: Check Labels
        uses: actions/github-script@v4
        id: check-labels
        with:
          script: |
            const script = require('./github-actions/issue-labels/check-labels.js')
            const checkLabels = script({g: github, c: context})
            return checkLabels

      # Post comment based on the previous action's results
      - name: Post Comment
        uses: actions/github-script@v4
        id: post-comment
        with:
            script: |
              const results = ${{ steps.check-labels.outputs.result }}
              const script = require('./github-actions/issue-labels/post-labels-comment.js')
              script({g: github, c:context}, results)