name: Issue Comment Trigger
on:
  issue_comment:
    types:
      - created

jobs:
  Add-Comment-To-Prework-Issue:
    if: ${{ github.event_name == 'issue_comment' && github.event.action == 'created'}}
    permissions:
      issues: write
    uses: ./.github/workflows/prework-issue-comment-reusable-workflow.yaml    secrets: inherit