name: Move Closed Issues
on:
  issues:
    types:
      - closed

jobs:
  Move-Closed-Issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1: Sort closed issues based on labels
      - name: Sort Closed Issues by Label
        uses: actions/github-script@v7
        id: sort-closed-issues
        with:
          script: |
            const script = require('./github-actions/move-closed-issues/sort-closed-issues.js');
            const sortIssues = script({context});
            return sortIssues;
          result-encoding: string

      # 2: Move closed issues
      - name: Move Closed Issue
        uses: actions/github-script@v7
        id: move-closed-issue
        with:
          github-token: ${{ secrets.HACKFORLA_GRAPHQL_TOKEN }}
          script: |
            const results = '${{ steps.sort-closed-issues.outputs.result }}';
            const script = require('./github-actions/move-closed-issues/move-closed-issues.js');
            script({github, context}, results);

      # 3: Get GraphQL ID of new status
      # - name: Get New Status Field ID
      #   uses: actions/github-script@v7
      #   id: get-status-id
      #   with:
      #     script: |
      #       const statusFieldId = require('./github-actions/utils/_data/status-field-ids.js');
      #       const sortedStatus = context.steps['sort-closed-issues'].outputs.result;
      #       const statusId = statusFieldId(sortedStatus);
      #       return statusId;

      # 4: Mutate the issue status using its itemId and the new status
      # - name: Mutate Issue Status
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       const mutateIssueStatus = require('./github-actions/utils/mutate-issue-status.js');
      #       const issueInfo = context.steps['query-issue-info'].outputs.result;
      #       const newStatusId = context.steps['get-status-id'].outputs.result;

      #       // Call the function to mutate the issue status
      #       await mutateIssueStatus(github, context, issueInfo.id, newStatusId);
