name: Move Closed Issues
on:
  issues:
    types:
      - closed
      
jobs:
  Move-Closed-Issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Sort Closed Issues by Label
        uses: actions/github-script@v7
        id: sort-closed-issues
        with:
          script: |
            const script = require('./github-actions/move-closed-issues/sort-closed-issues.js')
            const sortIssues = script({context})
            return sortIssues
          result-encoding: string
          
      # Post-migration to Projects Beta:
      # Move-Closed-Issues to "QA" column by default; OR move to "Done" based on `sort-closed-issues.js`
      - name: Move Closed Issues
        run: echo "Based on its labels, issue should be sorted to 'status' of '${{ steps.sort-closed-issues.outputs.result }}'" 
        
