name: Schedule Monthly- Reopen Issue
on: 
  issues:
    types: [reopened]

jobs:
  # Checks to see whether the title of the reopened issue contains the words 'Review Inactive Team Members' 
  First-Pass:
    if: ${{ contains(github.event.issue.title, 'Review Inactive Team Members') }}
    runs-on: ubuntu-latest
    steps:  
      - name: Check comment 
        id: check-comment
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = ${{ github.event.issue.number }}
            console.log("The issue number is: " + issueNumber)
            return issueNumber

      # Apply the `ready for dev lead` label
      - name: Add `ready for dev lead` label
        id: add-dev-lead
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.check-comment.outputs.result }},
              labels: ['ready for dev lead'],
            });
            console.log("Add the `ready for dev lead` label.")

  # Moves reopened issue to 'Questions/ In Review" column
  Move-Reopened-Issue:
    needs: First-Pass
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.title, 'Review Inactive Team Members') }} 
    steps:
      - name: Move Reopened Issue
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Project Board
          column: 'Questions / In Review'
          repo-token: ${{ secrets.TEST_GHAS }}
