name: Update Label Directory

# This action updates github-actions/utils/_data/label-directory.json
on:
  label:
    types: [edited, created, deleted]

jobs:
  Update-Label-Directory:
    runs-on: ubuntu-latest
    if: github.repository == 'hackforla/website'
    
    steps:
     - uses: actions/checkout@v4
     - name: Dump context
       env: 
         GITHUB_CONTEXT: ${{ toJson(github) }} 
       run: echo "GITHUB_CONTEXT defined"
    
     - name: Send context
       uses: actions/github-script@v7
       id: send-context
       with:
        github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
        script: |
          const script = require('./github-actions/utils/update-label-directory.js')
          script({g: github, c: context})

     - name: Update label directory
       uses: stefanzweifel/git-auto-commit-action@v5.0.0
       with:
         # Glob pattern of file to commit, and opt. commit message + author
         file_pattern: github-actions/utils/_data/label-directory.json
         commit_message: Update label directory
         commit_author: GitHub Actions Bot <hackforla-bot@hackforla.org> 
