# This workflow updates `github-actions/utils/_data/label-directory.json`
# and the Google Sheets doc `Website Labels 'Source of Truth'` at URL below

name: Update Label Directory

on:
  label:
    types: [edited, created, deleted]

jobs:
  Update-Label-Directory:
    runs-on: ubuntu-latest
    # if: github.repository == 'hackforla/website'                 << FIX BEFORE MERGING. FIX URL line 40 BELOW
    if: github.repository == 't-will-gillis/website'
    steps:
     - uses: actions/checkout@v4
       with:
        token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
        
     - name: Dump context
       env: 
         GITHUB_CONTEXT: ${{ toJson(github) }} 
       run: echo "GITHUB_CONTEXT defined"
    
     - name: Update label directory
       id: update-label-directory
       uses: actions/github-script@v7
       with:
        github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
        script: |
          const script = require('./github-actions/utils/update-label-directory.js')
          const labelPacket = script({g: github, c: context})
          return labelPacket

     # Note the the URL below matches the *current* deployment URL of the Apps Script associated 
     # with the 'Source of Truth' Label spreadsheet. (If something is broken, check this link first)
     - name: Send POST request to Google Apps Script
       if: steps.update-label-directory.outputs.result != ''
       run: |
         curl -X POST "https://script.google.com/macros/s/AKfycbxdrYljmu5bUpKxa7M2fRut8jH4ulT42fmbQbKn-9Tm3jdajqGpF65gkuAaxpd983cI/exec" \
           -H "Content-Type: application/json" \
           -d '${{ steps.update-label-directory.outputs.result }}'

     # Before next step, run `git pull` so that branch is current
     - name: Pull latest changes from gh-pages
       run: git pull
      
     - name: Commit changes to JSON Label Directory
       uses: stefanzweifel/git-auto-commit-action@v5.0.1
       with:
         # Glob pattern of file to commit, and opt. commit message + author
         file_pattern: github-actions/utils/_data/label-directory.json
         commit_message: Update label directory
         commit_author: GitHub Actions Bot <hackforla-bot@hackforla.org> 
