name: WR Pull Request Trigger
on:
  workflow_run:
    workflows: ["Pull Request Trigger"]
    types: [completed]

permissions:
    contents: read
    issues: write
    pull-requests: write

jobs:
  post-pr-comment:
    runs-on: ubuntu-latest
    env:
      ARTIFACT_NAME: 'pr-comment'
      SCRIPT_PATH: './github-actions/trigger-pr/check-linked-issue.js'
    steps:
      - uses: actions/checkout@v7
      - name: Download PR comment artifact
        id: download-pr-comment-artifact
        uses: actions/github-script@v9
        with:
          script: |
            const { downloadPRCommentArtifact } = require('${{ env.SCRIPT_PATH }}');
            await downloadPRCommentArtifact({ github, context }, '${{ env.ARTIFACT_NAME }}');
      - name: Extract artifact
        id: extract-artifact
        run: unzip '${{ env.ARTIFACT_NAME }}.zip'
      - name: Post comment to PR
        id: post-comment-to-pr
        uses: actions/github-script@v9
        with:
          script: |
            const { postPRComment } = require('${{ env.SCRIPT_PATH }}');
            await postPRComment({ github, context, core }, '${{ env.ARTIFACT_NAME }}.json');
