name: WR Schedule Monthly

on:
  workflow_run:
    workflows: ['Schedule Monthly']
    types: [completed]

jobs:
  Create-New-Issue:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "The 'Schedule Monthly' workflow succeeded. Continuing."
      - uses: actions/checkout@v6

      # Creates a new issue in 'hackforla/website' repo with the saved lists
      - name: Create new issue
        id: create-new-issue
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
          script: |
            const script = require('./github-actions/trigger-schedule/list-inactive-members/create-new-issue.js');
            const newIssue = script({g: github, c: context});
            return newIssue;

  Close-New-Issue:
    needs: Create-New-Issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      # Automatically close this last issue- that is, the issue just created by 'Schedule Monthly' 
      - name: Auto close issue
        run: gh issue close "${{ steps.create-new-issue.outputs.result }}"
        env:
          GH_TOKEN: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}
